apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      serviceAccountName: prometheus
      serviceAccount: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.50.1
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus" # 指定tsdb数据路径
        - "--storage.tsdb.retention.time=2d"  #何时删除旧数据，默认为 15 天
        - "--web.enable-lifecycle" # 支持热更新，直接执行localhost:9090/-/reload立即生效
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/etc/prometheus"
          name: prometheus-config
        - mountPath: "/prometheus"  # 指定tsdb数据路径
          name: prometheus-storage
      securityContext: # 设置容器运行用户为root
        runAsUser: 0  # 默认为0
      volumes:
      - name: prometheus-storage  
        persistentVolumeClaim:
          claimName: prometheus
      - name: prometheus-config
        configMap:
          name: prometheus-config


#   - "--config.file=/etc/prometheus/prometheus.yml"
#   - "--storage.tsdb.path=/prometheus"  # 指定tsdb数据路径
#   - "--storage.tsdb.retention.time=24h"
#   - "--web.enable-admin-api"  # 控制对admin HTTP API的访问，其中包括删除时间序列等功能
#   - "--web.enable-lifecycle"  # 支持热更新，直接执行localhost:9090/-/reload立即生效
#   - "--web.console.libraries=/usr/share/prometheus/console_libraries"
#   - "--web.console.templates=/usr/share/prometheus/consoles"