apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-node-exporter
spec:
  selector:
    matchLabels:
      name: k8s-node-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
        prometheus.io/path: 'metrics'
      labels:
        name: k8s-node-exporter
    spec:
      containers:
      - image: prom/node-exporter:v1.8.1
        imagePullPolicy: IfNotPresent
        name: k8s-node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
      hostNetwork: true
      hostPID: true
