apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    name: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    name: prometheus
  type: NodePort
