# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
repos:
  - repo: local
    hooks:
      - id: protect-protected-file
        name: Protect alertmanager-config.yaml
        entry: bash protect-protected-file.sh
        language: system
        stages: [commit]