## docs https://www.qikqiak.com/k8strain/monitor/grafana/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana
      containers:
        - name: grafana
          image:  grafana/grafana:10.2.4
          imagePullPolicy: IfNotPresent
          # 设置环境变量 GF_SECURITY_ADMIN_USER 与 GF_SECURITY_ADMIN_PASSWORD
          env:
          - name: GF_SECURITY_ADMIN_USER
            value: "admin"
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: admin321
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          readinessProbe:
            failureThreshold: 10  # 默认10次
            httpGet:  # 默认httpGet
              path: /api/health
              port: 3000
            initialDelaySeconds: 60 # 默认10秒
            periodSeconds: 10  # 默认10秒
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
      securityContext: # 设置容器运行用户为root
        runAsUser: 0  # 默认为0
