apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base 
- dr.yaml
namespace: dev
nameSuffix: -dev
commonLabels:
  app: blog-web-app
images:
- name: default_image
  newName: costa92/my-blog
  newTag: "local-20231111194616"
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
  path: deployment-patch.yaml
- target:
    version: v1 
    kind: Service 
  path: service-patch.yaml