apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- definition.yaml
- traefik.yaml
- account.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- middleware.yaml
- ingressroute.yaml
# - argo-Ingress-route.yaml  # 安装 argo 时需要
