apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- argocd.yaml 
## changes to config maps
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yaml  
namespace: argocd
