apiVersion: v1
kind: ConfigMap
metadata:
  name: dtm-conf
  labels:
    app: dtm
data:
  config.yaml: |-
    Store:
      Driver: mysql # 此处以 mysql 为例，其他数据库可自行替换
      Host: mariadb-0.mariadb.default.svc.cluster.local 
      Port: 3306
      User: root
      Password: krm(#)666
