apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: blog-web-dev
spec:
  parentRefs:
  - name: blog-web-gateway
  hostnames: 
  - hello-world.local
  rules:
  - matches:
    - path:
        type: Exact
        value: /
    backendRefs:
    - name: blog-web-service-dev
      port: 80
      # weight: 100