apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: blog-web-dev
  namespace: dev  # namespace where the gateway is deployed
  labels:
    app: blog-web
spec:
  parentRefs:   #绑定 Gateway 监听项
  - name: blog-web-gateway
  hostnames:     #为路由配置域名
  - hello-world.local  #可配置泛域名,可配置多个
  - traefik.test.com
  rules: #配置详细的路由规则，可配置多个，下面有对各种规则类型的详细解析
  - matches:  #匹配条件
    - path: #路径匹配
        type: PathPrefix  #路径类型：Exact 完全匹配/PathPrefix 前缀匹配/RegularExpression 正则匹配
        value: /
    backendRefs:  #后端路由
    - name: blog-web-service-dev # service 名称
      port: 80  #service 端口
      # weight: 100  #权重
