# apiVersion: gateway.networking.k8s.io/v1beta1
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: blog-web-vs
  namespace: dev
spec:
  hosts:
  - "traefik.test.com"
  gateways:
  - blog-web-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host:  blog-web-service-dev.dev.svc.cluster.local  # service 名称
      weight: 25
        # subset: stable  # service 子集
    - destination:
        host:  sammy-app-dev.dev.svc.cluster.local  # service 名称
      weight: 75