apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-app
  labels:
    app: base-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-app
  template:
    metadata:
      labels:
        app: base-app
    spec:
      containers:
      - name: server
        image: default_image
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: "128Mi"
          limits:
            cpu: 100m
            memory: "256Mi"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
