apiVersion: v1
kind: Service
metadata:
  name: base-service-dev
  labels:
    app: base-app
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP 
      port: 80
      targetPort: 8080