apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sammy-app
resources:
- ../../../base
- configmap.yaml 
# - service.yaml 
images:
- name: default_image
  newName: nginx
  newTag: "1.17"
namespace: dev
nameSuffix: -dev
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
  path: deployment-patch.yaml
- target:
    version: v1 
    kind: Service 
    name: my-service
  path: service-patch.yaml
