apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sammy-app
resources:
- ../../../base
- service.yaml
images:
- name: default_image
  newName: nginx
  newTag: "1.18"
namespace: dev
nameSuffix: -dev
patches:
- path: configmap.yaml
- path: service.yaml
